use soroban_sdk::{symbol_short, Symbol};

/// Custom error types for the QuickLendX contract
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum QuickLendXError {
    // Core errors
    InvoiceNotFound = 1000,
    InvoiceAmountInvalid = 1001,
    InvalidAmount = 1002,
    InvalidStatus = 1003,
    Unauthorized = 1004,
    NotAdmin = 1005,
    StorageKeyNotFound = 1006,
    BusinessNotVerified = 1007,
    PaymentTooLow = 1008,
    OperationNotAllowed = 1009,
    InsufficientFunds = 1010,
    InvalidAddress = 1011,
    InvalidDescription = 1012,
    InvoiceDueDateInvalid = 1013,
    NotInvestor = 1014,
    NotBusinessOwner = 1015,
    InvalidCurrency = 1016,
    InvalidTimestamp = 1017,
    StorageError = 1018,
    PlatformAccountNotConfigured = 1019,
    InvalidCoveragePercentage = 1020,
    InvalidRating = 1021,
    NotFunded = 1022,
    AlreadyRated = 1023,
    NotRater = 1024,
    KYCAlreadyPending = 1025,
    KYCAlreadyVerified = 1026,
    KYCNotFound = 1027,
    InvalidKYCStatus = 1028,
    AuditLogNotFound = 1029,
    AuditIntegrityError = 1030,
    AuditQueryError = 1031,
    InvalidFeeConfiguration = 1032,
    TreasuryNotConfigured = 1033,
    InvalidFeeBasisPoints = 1034,
    InvalidTag = 1035,
    TagLimitExceeded = 1036,
    DisputeNotFound = 1037,
    DisputeAlreadyExists = 1038,
    DisputeNotAuthorized = 1039,
    DisputeAlreadyResolved = 1040,
    DisputeNotUnderReview = 1041,
    InvalidDisputeReason = 1042,
    InvalidDisputeEvidence = 1043,
    NotificationNotFound = 1044,
    NotificationBlocked = 1045,
    InvoiceAlreadyFunded = 1046,
    InvoiceNotAvailableForFunding = 1047,
    InvoiceNotFunded = 1048,
    InvoiceAlreadyDefaulted = 1049,
    ProtocolPaused = 1050,
}

impl From<QuickLendXError> for Symbol {
    fn from(error: QuickLendXError) -> Self {
        match error {
            QuickLendXError::InvoiceNotFound => symbol_short!("INV_NF"),
            QuickLendXError::InvoiceAmountInvalid => symbol_short!("INV_AI"),
            QuickLendXError::InvalidAmount => symbol_short!("INV_AMT"),
            QuickLendXError::InvalidStatus => symbol_short!("INV_ST"),
            QuickLendXError::Unauthorized => symbol_short!("UNAUTH"),
            QuickLendXError::NotAdmin => symbol_short!("NOT_ADM"),
            QuickLendXError::StorageKeyNotFound => symbol_short!("KEY_NF"),
            QuickLendXError::BusinessNotVerified => symbol_short!("BUS_NV"),
            QuickLendXError::PaymentTooLow => symbol_short!("PAY_LOW"),
            QuickLendXError::OperationNotAllowed => symbol_short!("OP_NA"),
            QuickLendXError::InsufficientFunds => symbol_short!("INSUF"),
            QuickLendXError::InvalidAddress => symbol_short!("INV_ADR"),
            QuickLendXError::InvalidDescription => symbol_short!("INV_DS"),
            QuickLendXError::InvoiceDueDateInvalid => symbol_short!("INV_DI"),
            QuickLendXError::NotInvestor => symbol_short!("NOT_INV"),
            QuickLendXError::NotBusinessOwner => symbol_short!("NOT_OWN"),
            QuickLendXError::InvalidCurrency => symbol_short!("INV_CR"),
            QuickLendXError::InvalidTimestamp => symbol_short!("INV_TM"),
            QuickLendXError::StorageError => symbol_short!("STORE"),
            QuickLendXError::PlatformAccountNotConfigured => symbol_short!("PLT_NC"),
            QuickLendXError::InvalidCoveragePercentage => symbol_short!("INS_CV"),
            QuickLendXError::InvalidRating => symbol_short!("INV_RT"),
            QuickLendXError::NotFunded => symbol_short!("NOT_FD"),
            QuickLendXError::AlreadyRated => symbol_short!("ALR_RT"),
            QuickLendXError::NotRater => symbol_short!("NOT_RT"),
            QuickLendXError::KYCAlreadyPending => symbol_short!("KYC_PD"),
            QuickLendXError::KYCAlreadyVerified => symbol_short!("KYC_VF"),
            QuickLendXError::KYCNotFound => symbol_short!("KYC_NF"),
            QuickLendXError::InvalidKYCStatus => symbol_short!("KYC_IS"),
            QuickLendXError::AuditLogNotFound => symbol_short!("AUD_NF"),
            QuickLendXError::AuditIntegrityError => symbol_short!("AUD_IE"),
            QuickLendXError::AuditQueryError => symbol_short!("AUD_QE"),
            QuickLendXError::InvalidFeeConfiguration => symbol_short!("FEE_CFG"),
            QuickLendXError::TreasuryNotConfigured => symbol_short!("TRS_NC"),
            QuickLendXError::InvalidFeeBasisPoints => symbol_short!("FEE_BPS"),
            QuickLendXError::InvalidTag => symbol_short!("INV_TAG"),
            QuickLendXError::TagLimitExceeded => symbol_short!("TAG_LIM"),
            QuickLendXError::DisputeNotFound => symbol_short!("DSP_NF"),
            QuickLendXError::DisputeAlreadyExists => symbol_short!("DSP_EX"),
            QuickLendXError::DisputeNotAuthorized => symbol_short!("DSP_NA"),
            QuickLendXError::DisputeAlreadyResolved => symbol_short!("DSP_RS"),
            QuickLendXError::DisputeNotUnderReview => symbol_short!("DSP_UR"),
            QuickLendXError::InvalidDisputeReason => symbol_short!("DSP_RN"),
            QuickLendXError::InvalidDisputeEvidence => symbol_short!("DSP_EV"),
            QuickLendXError::NotificationNotFound => symbol_short!("NOT_NF"),
            QuickLendXError::NotificationBlocked => symbol_short!("NOT_BL"),
            QuickLendXError::InvoiceAlreadyFunded => symbol_short!("INV_AF"),
            QuickLendXError::InvoiceNotAvailableForFunding => symbol_short!("INV_NAF"),
            QuickLendXError::InvoiceNotFunded => symbol_short!("INV_NDF"),
            QuickLendXError::InvoiceAlreadyDefaulted => symbol_short!("INV_AD"),
            QuickLendXError::ProtocolPaused => symbol_short!("PAUS"),
        }
    }
}
