#[cfg(test)]
mod tests {
    use crate::payment_token_policy::*;
    const ADMIN: TokenPolicyAdmin = TokenPolicyAdmin { address: [9; 32], version: 4 };
    fn request(n: u8, enabled: bool, version: u32) -> TokenUpdateRequest { TokenUpdateRequest { token: [n; 32], enabled, expected_version: version } }

    #[test] fn empty_batch_is_stable() { let mut list = TokenAllowlist::empty(); let result = apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[]).unwrap(); assert_eq!(result, snapshot(&list)); }
    #[test] fn batch_updates_existing_entry() { let mut list = TokenAllowlist::empty(); apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, true, 0)]).unwrap(); let result = apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, false, 1)]).unwrap(); assert_eq!((result.configured, result.enabled), (1, 0)); assert_eq!(list.find([1; 32]).unwrap().version, 2); }
    #[test] fn batch_reenables_entry() { let mut list = TokenAllowlist::empty(); apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, false, 0)]).unwrap(); apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, true, 1)]).unwrap(); assert!(list.find([1; 32]).unwrap().enabled); }
    #[test] fn batch_stale_entry_fails() { let mut list = TokenAllowlist::empty(); apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, true, 0)]).unwrap(); assert!(apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, false, 0)]).is_err()); assert!(list.find([1; 32]).unwrap().enabled); }
    #[test] fn batch_fills_allowlist() { let mut list = TokenAllowlist::empty(); let updates = [request(1, true, 0), request(2, true, 0), request(3, true, 0), request(4, true, 0), request(5, true, 0), request(6, true, 0), request(7, true, 0), request(8, true, 0)]; assert_eq!(apply_batch_updates(ADMIN.address, ADMIN, &mut list, &updates).unwrap().configured, 8); }
    #[test] fn batch_over_capacity_fails() { let mut list = TokenAllowlist::empty(); for n in 1..=8 { list.insert(TokenConfig { token: [n; 32], enabled: true, version: 1, request_key: [0; 32], previous_enabled: false }).unwrap(); } assert!(apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(9, true, 0)]).is_err()); }
    #[test] fn snapshot_digest_changes_on_update() { let mut list = TokenAllowlist::empty(); let first = apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, true, 0)]).unwrap(); let second = apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, false, 1)]).unwrap(); assert_ne!(first.digest, second.digest); }
    #[test] fn snapshot_highest_version_is_reported() { let mut list = TokenAllowlist::empty(); apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, true, 0)]).unwrap(); let result = apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, false, 1)]).unwrap(); assert_eq!(result.highest_version, 2); }
    #[test] fn snapshot_enabled_count_tracks_updates() { let mut list = TokenAllowlist::empty(); apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, true, 0), request(2, true, 0)]).unwrap(); let result = apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, false, 1)]).unwrap(); assert_eq!(result.enabled, 1); }
    #[test] fn rotation_requires_new_identity() { let next = rotate_admin(ADMIN.address, ADMIN, [7; 32]).unwrap(); assert_eq!(next.version, 5); }
    #[test] fn old_admin_cannot_rotate_again() { let next = rotate_admin(ADMIN.address, ADMIN, [7; 32]).unwrap(); assert_eq!(rotate_admin(ADMIN.address, next, [8; 32]), Err(TokenPolicyError::Unauthorized)); }
    #[test] fn new_admin_can_rotate_again() { let next = rotate_admin(ADMIN.address, ADMIN, [7; 32]).unwrap(); assert_eq!(rotate_admin(next.address, next, [8; 32]).unwrap().version, 6); }
    #[test] fn rotation_overflow_fails() { let current = TokenPolicyAdmin { address: ADMIN.address, version: u32::MAX }; assert_eq!(rotate_admin(ADMIN.address, current, [7; 32]), Err(TokenPolicyError::InvalidVersion)); }
    #[test] fn batch_validation_allows_empty() { assert!(validate_update_batch(ADMIN.address, ADMIN, &[]).is_ok()); }
    #[test] fn batch_validation_rejects_zero_admin() { assert_eq!(validate_update_batch([0; 32], ADMIN, &[]), Err(TokenPolicyError::InvalidAdmin)); }
    #[test] fn batch_validation_rejects_wrong_admin() { assert_eq!(validate_update_batch([8; 32], ADMIN, &[]), Err(TokenPolicyError::Unauthorized)); }
    #[test] fn batch_snapshot_is_consistent_after_failed_update() { let mut list = TokenAllowlist::empty(); apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, true, 0)]).unwrap(); let before = snapshot(&list); assert!(apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, false, 0), request(2, true, 0)]).is_err()); assert_eq!(snapshot(&list), before); }
    #[test] fn batch_keeps_token_identity() { let mut list = TokenAllowlist::empty(); apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(4, true, 0)]).unwrap(); assert_eq!(list.find([4; 32]).unwrap().token, [4; 32]); }
    #[test] fn batch_disabled_token_remains_configured() { let mut list = TokenAllowlist::empty(); let result = apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(4, false, 0)]).unwrap(); assert_eq!(result.configured, 1); assert_eq!(result.enabled, 0); }
    #[test] fn batch_new_token_starts_version_one() { let mut list = TokenAllowlist::empty(); apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(5, true, 0)]).unwrap(); assert_eq!(list.find([5; 32]).unwrap().version, 1); }
    #[test] fn batch_reenable_is_new_version() { let mut list = TokenAllowlist::empty(); apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(6, false, 0)]).unwrap(); apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(6, true, 1)]).unwrap(); assert_eq!(list.find([6; 32]).unwrap().version, 2); }
    #[test] fn snapshot_counts_only_enabled() { let mut list = TokenAllowlist::empty(); apply_batch_updates(ADMIN.address, ADMIN, &mut list, &[request(1, false, 0), request(2, true, 0)]).unwrap(); assert_eq!(snapshot(&list).enabled, 1); }
}
